### ISSUE TITLE
Map still does not center on location when clicked on from the home screen

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#403] opened 2015-06-25 14:52 UTC
![image](https://cloud.githubusercontent.com/assets/12200440/8357297/3a09b352-1b28-11e5-82f9-12f350fa0448.png)

It does center once you click "back" and then have a list, and click through the list of destinations, which is good.

**Comment by flibbertigibbet** [comment] 2015-06-25 15:22
Duplicate of #340.  Fixed in #399, which has not been deployed yet.

**Closed by flibbertigibbet** 2015-06-25 15:22 UTC
