### ISSUE TITLE
share your ride, link to turn by turn directions 

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#320] opened 2015-05-20 13:57 UTC
![image](https://cloud.githubusercontent.com/assets/12200440/7727416/99790cca-fed6-11e4-9fd9-054372628a0b.png)
Black bar through the GoPhillyGo logo

**Comment by jbranigan** [comment] 2015-05-20 14:44
Duplicate of https://github.com/azavea/cac-tripplanner/issues/311, merged and fixed yesterday. We'll push this change and others today.

**Closed by jbranigan** 2015-05-20 14:44 UTC
Labels: duplicate
