### ISSUE TITLE
Wrong starting location

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#467] opened 2016-07-05 14:38 UTC
http://gophillygo.org/map/directions?origin=39.88753774946866%2C-75.184854044178&destination=40.15454607300046%2C-75.22156855999964&originText=135%20S%2019th%20St%2C%20Philadelphia%2C%20Pennsylvania%2C%20USA&destinationText=Ambler%2C%20Pennsylvania%2C%20United%20States&method=directions&mode=TRANSIT%2CWALK&arriveBy=true&maxWalk=2&wheelchair=false&bikeTriangle=neutral

Shows 135 South 19th Street as somewhere in the Navy Yard, when it should be at 19th and Walnut.

**Comment by nickrogers** [comment] 2016-07-05 14:40
![image](https://cloud.githubusercontent.com/assets/12200440/16588424/dcfd1d0a-429c-11e6-8b88-a726a03c8aad.png)

**Comment by jbranigan** [comment] 2016-07-05 18:22
I tried several times to reproduce this, and couldn't. I cleared the origin point, typed the name, and the correct address was produced. How was the error originally produced?

http://gophillygo.org/map/directions?origin=39.95069983023404%2C-75.17212326917274&destination=40.15454607300046%2C-75.22156855999964&originText=135%20S%2019th%20St%2C%20Philadelphia%2C%20Pennsylvania%2C%2019103&destinationText=Ambler%2C%20Pennsylvania%2C%20United%20States&method=directions&mode=TRANSIT%2CWALK&arriveBy=true&maxWalk=2&wheelchair=false&bikeTriangle=neutral

**Comment by nickrogers** [comment] 2016-07-05 18:24
I tried again after clearing the start location and also could not duplicate it. It was auto-filled as the most recent start location I had used.

**Comment by nickrogers** [comment] 2016-07-05 18:25
But before I cleared it I tried another end location, keeping the origin in tact, and it started me in the same (incorrect) place.

**Comment by flibbertigibbet** [comment] 2016-07-05 19:45
I saw the Navy Yard location this morning, but it appears to be correct now. In any case, the location comes from the geocoding service and is not something under our control; perhaps it was a transient issue with their service that has since been addressed.

**Comment by jbranigan** [comment] 2016-07-05 19:52
Closing this for now - we'll keep an eye on the geocoding service

**Closed by jbranigan** 2016-07-05 19:52 UTC
