### ISSUE TITLE
destination selectiosn aren't working for directions

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#419] opened 2015-06-29 19:04 UTC
tried this:
![image](https://cloud.githubusercontent.com/assets/12200440/8415909/fe7f2790-1e6f-11e5-816c-56dcdbd42652.png)
 and got this:
![image](https://cloud.githubusercontent.com/assets/12200440/8415917/1204a542-1e70-11e5-83a7-a0763207464e.png)

**Comment by flibbertigibbet** [comment] 2015-06-29 19:08
Duplicate of #417

**Comment by jbranigan** [comment] 2015-06-29 19:09
We just fixed this - it hasn't been updated on the server yet.

**Closed by flibbertigibbet** 2015-06-29 19:08 UTC
